błąd: "Błąd"
widżet kontaktowy/feedback: 'Widżet kontaktowy\/informacji zwrotnej'
newsletter: "Newsletter"
otagowany link wewnętrzny: "Otagowany link wewnętrzny"
popup: "Wyskakujące okienko"
push: "Powiadomienie push"
scrollujący filmik: "Scrollujący filmik"
strzałka: "Strzałka"
tło autopromocyjne: "Tło zawierające autopromocję"
inny element: "Inny element"
powrotowy tytuł: "Tytuł strony zachęcający do powrotu"
prenumerata: "Reklama prenumeraty\/e-wydania gazety"
pytanie: "Pytanie"
ulepszenie: "Ulepszenie"
