addons:
  apt:
    packages:
    - libtypes-path-tiny-perl
    - locales
    - language-pack-pl
script:
- "./scripts/version_checksum_update_Travis.sh ./PPB.txt"
env:
  global:
    secure: rQnnpPrB8eYE/PFuNBr4Si8bvXye8BFhKB2c2s62CzYuBvPUGSEBlVmoJwUi9LE8EKa6XM237qEHTsIoKfCJLAULhpyxH4WyF6FFIwpllq/Wb2dHZB3txjGLDKAv19YNLQPAgrr+Fg33uGyJ0j6HtGRwXnEeaSO3/tj4FpmSJIIO6ia6QXA95aCnOA1yXWNAEEOfSyFX6ZI4WX2tYC8+aMrTsIJidSN+wl6WMYpalJvXQcdtWRAhjReZ3nI5Lxb/qFgOAF7dV5mxBNzuOyGabs7rS8ZMc+cldNK9mY2SyJRo/l7uBz1PYh1rISsQbFHO+dCWetC7GSP8Kv0+Fn2ZV4IZLZxszTHXA0hJV69b6AvRSdlLEKwmosGbYkcwpeZ8uRIMTzSKYqAEwaW0JlhkdrtoztGUdr0Vkut0QHOVu+7294J6Ddxr19JjPUMxjUVPomSmyDCmDa5EzSfHiCe/XLLDMsJivSQcbsf3C1AGsnrJ4lyPbC7gNeCTWnyeWuF86iYxv00YhRWl2Vfw1nouwEbbyLS2Gpn/MiQXl4PL5PoRvgsE6bqDUH8idijYPhRftM1jGvRpIvRIsQq/TgCyK7SuNHH+I56Tjm504RR8dx4pUmreNY2claro45JyUo0Grq4afuPB0v2NX7FbVeDkTkB+D2voq2+JEEE468oUBM4=
