name: Irytujące elementy i błędy
description: Polish form, annoying elements and bugs
body:
  - type: markdown
    attributes:
      value: |
        Dziękujemy za zgłoszenie do Polskich Filtrów Elementów Irytujących!
  - type: checkboxes
    id: problemType
    attributes:
      label: Typ elementu lub problemu
      description: |
        W przypadku pomyłki co do typu, proszę odznaczyć checkbox (przycisk wyboru) lub usunąć x i wstawić spację zamiast niego.
      options:
        - label: Wyskakujące okienko (popup)
        - label: Newsletter (nie popup)
        - label: Powiadomienie push (nie „zgoda na geolokalizację”)
        - label: Scrollujący filmik
        - label: Inny element (np. widget „następny artykuł”)
        - label: Widżet kontaktowy/informacji zwrotnej
        - label: Strzałka
        - label: Otagowany link wewnętrzny (niezgodny z tematem artykułu)
        - label: Tło zawierające autopromocję
        - label: Tytuł strony zachęcający do powrotu
        - label: Reklama prenumeraty/e-wydania gazety
        - label: Błąd
        - label: Pytanie
        - label: Ulepszenie
  - type: dropdown
    id: OS
    attributes:
      label: System operacyjny
      options:
        - Linux/Unix
        - Windows
        - macOS
        - Android
        - iOS
    validations:
      required: true
  - type: input
    id: webBrowser
    attributes:
      label: Przeglądarka internetowa
      placeholder: Pale Moon 29.2.1
    validations:
      required: true
  - type: input
    id: adblocker
    attributes:
      label: Bloker
      placeholder: uBlock Origin 1.16.4.29
    validations:
      required: true
  - type: textarea
    id: myfilters
    attributes:
      label: Używane listy filtrów
      value: |
        1. EasyList
        2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
        3. Polskie Filtry Elementów Irytujących
        4. 
        5. 
    validations:
      required: true
  - type: textarea
    id: otherExtensions
    attributes:
      label: Inne rozszerzenia
      placeholder: Polish Cookie Consent 1.43.5
  - type: textarea
    id: specificLink
    attributes:
      label: Link bezpośredni
      description: |
        Wstaw tutaj link bezpośredni do strony, na której występuje element albo błąd.
      placeholder: http://www.biedronka.pl/newsletter
      render: markdown
  - type: textarea
    id: additionalInfo
    attributes:
      label: |
        Dodatkowe informacje mogące mieć znaczenie
      description: |
        Zrzuty ekranu, etapy odtworzenia problemu (co doprowadziło do błędu) albo twoja metoda rozwiązania problemu.
      placeholder: Proszę pana, na tej stronie wyskakuje cała masa okienek o jakiś promocjach i na dole pojawiają się jakieś strzałki. Coś tam też w kółko miga mi przed oczami, a w tle gra irytująca muzyczka. Od tego wszystkiego głowa mnie już boli, a komputer wariuje... .
  - type: checkboxes
    id: terms
    attributes:
      label: Zasady pisania
      options:
        - label: |
            Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)
          required: true
