name: Portier
on:
  issues:
    types: [labeled]

jobs:
  letsgo:
    if: github.event.label.name == 'zatwierdzone' || github.event.label.name == 'odrzucone'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
              var reason;
              var labels = context.payload.issue.labels;
              if(labels.some(e => e.name === "zatwierdzone")) {
                reason = "completed"
              }
              else {
                reason = "not_planned"
              }
              github.rest.issues.update({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      issue_number: context.issue.number,
                      state: "closed",
                      state_reason: reason
              })
