name: Aktualizacja listy

on:
  workflow_dispatch: null
  schedule:
    - cron: "30 23 * * 5"

jobs:
  Aktualizacja:
    runs-on: ubuntu-latest
    container: ghcr.io/filtersheroes/vichs_image:2.26.9-2
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          HelperForVICHS.sh PAF_arrows.txt PAF_backgrounds_self-adv_supp.txt PAF_backgrounds_self-advertising.txt PAF_contact_feedback_widgets_supp.txt PAF_contact_feedback_widgets.txt PAF_newsletters_supp.txt PAF_newsletters.txt PAF_other_elements_supp.txt PAF_other_widgets.txt PAF_pop-ups_supp.txt PAF_pop-ups.txt PAF_push_supp.txt PAF_push.txt PAF_scrolling_videos_supp.txt PAF_scrolling_videos.txt PAF_tagged_internal_links.txt PAF_comeback_titles.txt PAF_e_newspaper.txt PAF_supp.txt PPB.txt
