name: Aktualizacja listy

on:
  workflow_dispatch: null
  schedule:
    - cron: "30 15,19 * * *"
    - cron: "30 23 * * 5"

jobs:
  Aktualizacja:
    runs-on: ubuntu-latest
    container: ghcr.io/filtersheroes/sflb_image:3.0.11
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_HELPER_ID }}
          private-key: ${{ secrets.PRIVATE_APP_HELPER_KEY }}
      - env:
          GIT_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          SFLB.py PAF_arrows.txt PAF_backgrounds_self-adv_supp.txt PAF_backgrounds_self-advertising.txt PAF_contact_feedback_widgets_supp.txt PAF_contact_feedback_widgets.txt PAF_newsletters_supp.txt PAF_newsletters.txt PAF_other_elements_supp.txt PAF_other_widgets.txt PAF_pop-ups_supp.txt PAF_pop-ups.txt PAF_push_supp.txt PAF_push.txt PAF_scrolling_videos_supp.txt PAF_scrolling_videos.txt PAF_tagged_internal_links.txt PAF_comeback_titles.txt PAF_e_newspaper.txt PAF_supp.txt PPB.txt
